data:
  path:
    raw: data/raw
    interim: data/interim

datasets:
  tiny_shakespeare:
    url: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
    folder: ${data.path.raw}/tiny_shakespeare
    filename: input.txt
    file_path: ${datasets.tiny_shakespeare.folder}/${datasets.tiny_shakespeare.filename}

model:
  seed: 42
  test_split: 0.9
  bigram:
    batch_size: 32
    context_size: 8 # what is the maximum context length of predictions
    epochs: 1
    learning_rate: 1e-2
  gpt:
    size:
      large:
        batch_size: 64
        context_size: 256
        dropout: 0.2
        embeddings_size: 384
        epochs: 1
        head_size: 32 # either should be provided explicitly or calculated implicitly as embeddings_size / num_heads
        learning_rate: 3e-4
        num_heads: 6
        num_layers: 6
      small:
        batch_size: 32
        context_size: 8
        dropout: 0.2
        embeddings_size: 64
        epochs: 1
        learning_rate: 3e-4
        num_heads: 2
        num_layers: 2
        head_size: 8
