data:
  path:
    raw: data/raw
    interim: data/interim

datasets:
  tiny_shakespeare:
    url: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
    folder: ${data.path.raw}/tiny_shakespeare
    filename: input.txt
    file_path: ${datasets.tiny_shakespeare.folder}/${datasets.tiny_shakespeare.filename}

model:
  seed: 42
  bigram:
    batch_size: 32
    block_size: 8 # what is the maximum context length of predictions
    epochs: 1
    learning_rate: 1e-2
  gpt:
    config:
      full:
        batch_size: 64
        block_size: 256 # what is the maximum context length of predictions
        dropout: 0.2
        epochs: 1
        learning_rate: 3e-4
        n_embed: 384
        n_heads: 6
        n_layers: 6
      debug:
        batch_size: 32
        block_size: 8 # what is the maximum context length of predictions
        dropout: 0.2
        epochs: 1
        learning_rate: 3e-4
        n_embed: 64
        n_heads: 2
        n_layers: 2
