data:
  path:
    raw: data/raw
    interim: data/interim

datasets:
  tiny_shakespeare:
    url: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
    folder: ${data.path.raw}/tiny_shakespeare
    filename: input.txt
    file_path: ${datasets.tiny_shakespeare.folder}/${datasets.tiny_shakespeare.filename}

model:
  seed: 42
  small:
    batch_size: 32
    block_size: 8 # what is the maximum context length of predictions
    epochs: 1
    eval_interval: 300
    eval_iters: 200
    learning_rate: 1e-2
    max_iters: 3_000
